In [114]:
# Import the pandas library and read the Genotypes_capstone.csv file, using ';' as the delimiter.
import pandas as pd
genotypes = pd.read_csv("Genotypes_capstone.csv", sep=";")

# Define a function that takes a list of genotype values
# and returns a list of True/False indicating if each value is greater than 0.
def find_present_nucleotides(nucs_in_population):
    return [x > 0 for x in (nucs_in_population)]

def is_biallelic(row):
    # Call the 'find_present_nucleotides' function on specific columns for every population group
    # to create lists of True/False values.
    # Combine the True/False lists using the 'and' operator to create a total presence list.
    nuc_presence_total = [any(items) for items in 
                          zip(find_present_nucleotides(row[2:6]), 
                              find_present_nucleotides(row[6:10]), 
                              find_present_nucleotides(row[10:14]), 
                              find_present_nucleotides(row[14:18]))]
    return sum(nuc_presence_total) == 2


# Filter the genotypes to include only biallelic SNPs.
filtered_genotypes = genotypes[genotypes.apply(is_biallelic, axis=1)]
filtered_genotypes

,chromosome,position,pop1_A,pop1_T,pop1_G,pop1_C,pop2_A,pop2_T,pop2_G,pop2_C,pop3_A,pop3_T,pop3_G,pop3_C,pop4_A,pop4_T,pop4_G,pop4_C
5,HG916831.1,14867521,0,254,0,99,0,346,0,83,0,244,0,82,0,237,0,73
19,HG916831.1,14867535,0,0,473,0,0,11,533,0,0,0,407,0,0,5,381,0
33,HG916831.1,14867549,0,0,547,0,11,0,677,0,5,0,488,0,11,0,460,0
41,HG916831.1,14867557,0,569,0,8,0,706,0,15,0,486,0,22,0,467,0,22
52,HG916831.1,14867568,0,589,0,0,0,736,0,0,7,494,0,0,0,496,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55944,HG916850.1,9679382,0,730,0,0,0,469,0,11,0,430,0,0,0,552,0,9
55954,HG916850.1,9679392,656,0,14,0,438,0,0,0,399,0,0,0,521,0,0,0
55967,HG916850.1,9679405,10,0,0,550,0,0,0,393,0,0,0,325,6,0,0,411
55968,HG916850.1,9679406,0,0,539,15,0,0,391,0,0,0,321,0,0,0,405,7
55974,HG916850.1,9679412,0,434,0,24,0,348,0,22,0,254,0,34,0,330,0,21

In [115]:
print(f"Number of biallelic SNPs: {filtered_genotypes.shape[0]}")

Number of biallelic SNPs: 6592